data_list = [
    {"name": "Cristiano Ronaldo", "follower_count": 620, "description": "Portuguese footballer", "country": "Portugal"},
    {"name": "Leo Messi", "follower_count": 500, "description": "Argentine footballer", "country": "Argentina"},
    {"name": "Selena Gomez", "follower_count": 420, "description": "American singer and actress", "country": "USA"},
    {"name": "The Rock", "follower_count": 395, "description": "Actor and former wrestler", "country": "USA"},
    {"name": "Kylie Jenner", "follower_count": 400, "description": "Model and entrepreneur", "country": "USA"},
    {"name": "Kim Kardashian", "follower_count": 360, "description": "TV personality and entrepreneur", "country": "USA"},
    {"name": "Beyoncé", "follower_count": 315, "description": "Singer and songwriter", "country": "USA"},
    {"name": "Justin Bieber", "follower_count": 290, "description": "Canadian singer", "country": "Canada"},
    {"name": "Taylor Swift", "follower_count": 280, "description": "Singer and songwriter", "country": "USA"},
    {"name": "Neymar Jr", "follower_count": 220, "description": "Brazilian footballer", "country": "Brazil"},
    {"name": "Ariana Grande", "follower_count": 375, "description": "Singer and actress", "country": "USA"},
    {"name": "Billie Eilish", "follower_count": 110, "description": "Singer and songwriter", "country": "USA"},
    {"name": "Elon Musk", "follower_count": 185, "description": "Entrepreneur and CEO of Tesla", "country": "South Africa"},
    {"name": "Jeff Bezos", "follower_count": 95, "description": "Entrepreneur and founder of Amazon", "country": "USA"},
    {"name": "NASA", "follower_count": 90, "description": "American space agency", "country": "USA"},
    {"name": "Barack Obama", "follower_count": 130, "description": "Former US President", "country": "USA"},
    {"name": "Donald Trump", "follower_count": 85, "description": "Former US President", "country": "USA"},
    {"name": "Virat Kohli", "follower_count": 270, "description": "Indian cricketer", "country": "India"},
    {"name": "Priyanka Chopra", "follower_count": 85, "description": "Indian actress and model", "country": "India"},
    {"name": "Shakira", "follower_count": 88, "description": "Colombian singer", "country": "Colombia"},
    {"name": "Rihanna", "follower_count": 150, "description": "Singer and entrepreneur", "country": "Barbados"},
    {"name": "Eminem", "follower_count": 60, "description": "American rapper", "country": "USA"},
    {"name": "Drake", "follower_count": 145, "description": "Canadian rapper and singer", "country": "Canada"},
    {"name": "LeBron James", "follower_count": 160, "description": "American basketball player", "country": "USA"},
    {"name": "Kevin Hart", "follower_count": 175, "description": "Comedian and actor", "country": "USA"},
    {"name": "Dwayne Johnson", "follower_count": 395, "description": "Actor and former wrestler", "country": "USA"},
    {"name": "Zendaya", "follower_count": 130, "description": "Actress and singer", "country": "USA"},
    {"name": "Tom Holland", "follower_count": 75, "description": "Spider-Man actor", "country": "UK"},
    {"name": "Robert Downey Jr", "follower_count": 60, "description": "Iron Man actor", "country": "USA"},
    {"name": "Scarlett Johansson", "follower_count": 70, "description": "American actress", "country": "USA"},
    {"name": "Chris Hemsworth", "follower_count": 60, "description": "Thor actor", "country": "Australia"},
    {"name": "Will Smith", "follower_count": 75, "description": "Actor and singer", "country": "USA"},
    {"name": "Jackie Chan", "follower_count": 50, "description": "Actor and martial artist", "country": "China"},
    {"name": "Stephen Curry", "follower_count": 55, "description": "Basketball player", "country": "USA"},
    {"name": "Conor McGregor", "follower_count": 47, "description": "MMA fighter", "country": "Ireland"},
    {"name": "Mike Tyson", "follower_count": 20, "description": "Former boxer", "country": "USA"},
    {"name": "FIFA World Cup", "follower_count": 35, "description": "Football world cup tournament", "country": "International"},
    {"name": "Olympics", "follower_count": 30, "description": "Olympic games", "country": "International"},
    {"name": "Netflix", "follower_count": 40, "description": "Movie and series streaming service", "country": "USA"},
    {"name": "Spotify", "follower_count": 28, "description": "Music streaming service", "country": "Sweden"},
    {"name": "Tesla", "follower_count": 25, "description": "Electric car company", "country": "USA"},
    {"name": "Apple", "follower_count": 30, "description": "Technology company", "country": "USA"},
    {"name": "Samsung", "follower_count": 20, "description": "Electronics company", "country": "South Korea"},
    {"name": "Google", "follower_count": 55, "description": "Search engine and technology", "country": "USA"},
    {"name": "YouTube", "follower_count": 70, "description": "Video sharing platform", "country": "USA"},
    {"name": "Instagram", "follower_count": 65, "description": "Social media platform", "country": "USA"},
    {"name": "TikTok", "follower_count": 50, "description": "Short video social platform", "country": "China"},
    {"name": "Facebook", "follower_count": 45, "description": "Social media platform", "country": "USA"},
    {"name": "Twitter (X)", "follower_count": 35, "description": "Social media platform", "country": "USA"},
    {"name": "LinkedIn", "follower_count": 25, "description": "Professional social network", "country": "USA"},
    {"name": "ChatGPT", "follower_count": 15, "description": "OpenAI artificial intelligence", "country": "USA"},
    {"name": "DeepSeek", "follower_count": 8, "description": "Chinese AI assistant", "country": "China"},
    {"name": "GTA 6", "follower_count": 12, "description": "Upcoming video game", "country": "USA"},
    {"name": "Fortnite", "follower_count": 22, "description": "Online video game", "country": "USA"},
    {"name": "Minecraft", "follower_count": 18, "description": "Popular video game", "country": "Sweden"},
    {"name": "Valorant", "follower_count": 10, "description": "Shooter video game", "country": "USA"},
    {"name": "Call of Duty", "follower_count": 14, "description": "First-person shooter game", "country": "USA"},
    {"name": "Harry Potter", "follower_count": 45, "description": "Book and film series", "country": "UK"},
    {"name": "Star Wars", "follower_count": 40, "description": "Sci-fi film franchise", "country": "USA"},
    {"name": "Marvel", "follower_count": 60, "description": "Superhero franchise", "country": "USA"},
    {"name": "DC Comics", "follower_count": 35, "description": "Superhero franchise", "country": "USA"},
    {"name": "Naruto", "follower_count": 30, "description": "Popular Japanese anime", "country": "Japan"},
    {"name": "Attack on Titan", "follower_count": 15, "description": "Popular Japanese anime", "country": "Japan"},
    {"name": "One Piece", "follower_count": 25, "description": "Popular anime and manga", "country": "Japan"},
    {"name": "Pokemon", "follower_count": 35, "description": "Game and anime franchise", "country": "Japan"},
    {"name": "Squid Game", "follower_count": 20, "description": "Korean Netflix series", "country": "South Korea"},
    {"name": "Money Heist", "follower_count": 18, "description": "Spanish TV series", "country": "Spain"},
    {"name": "Stranger Things", "follower_count": 22, "description": "Sci-fi Netflix series", "country": "USA"},
    {"name": "Wednesday", "follower_count": 12, "description": "Netflix series", "country": "USA"},
    {"name": "The Last of Us", "follower_count": 10, "description": "Popular game and series", "country": "USA"},
    {"name": "God of War", "follower_count": 8, "description": "Popular video game", "country": "USA"},
    {"name": "The Witcher", "follower_count": 12, "description": "Game and TV series", "country": "Poland"},
    {"name": "Cyberpunk 2077", "follower_count": 9, "description": "Video game", "country": "Poland"},
    {"name": "Red Dead Redemption", "follower_count": 11, "description": "Western video game", "country": "USA"},
    {"name": "Elden Ring", "follower_count": 7, "description": "Award-winning video game", "country": "Japan"},
    {"name": "Zelda", "follower_count": 10, "description": "Popular video game franchise", "country": "Japan"},
    {"name": "Super Mario", "follower_count": 20, "description": "Classic video game", "country": "Japan"},
    {"name": "Sonic the Hedgehog", "follower_count": 12, "description": "Video game franchise", "country": "Japan"},
    {"name": "The Beatles", "follower_count": 25, "description": "Legendary music band", "country": "UK"},
    {"name": "Queen", "follower_count": 30, "description": "Rock band", "country": "UK"},
    {"name": "Michael Jackson", "follower_count": 40, "description": "Legendary singer and artist", "country": "USA"},
    {"name": "Elvis Presley", "follower_count": 15, "description": "Rock and roll singer", "country": "USA"},
    {"name": "Madonna", "follower_count": 20, "description": "Singer and artist", "country": "USA"},
    {"name": "Lady Gaga", "follower_count": 55, "description": "Singer and actress", "country": "USA"},
    {"name": "K-pop", "follower_count": 50, "description": "Korean music genre", "country": "South Korea"},
    {"name": "BTS", "follower_count": 75, "description": "Korean music group", "country": "South Korea"},
    {"name": "BLACKPINK", "follower_count": 90, "description": "Korean music group", "country": "South Korea"},
    {"name": "Psy", "follower_count": 25, "description": "Korean singer (Gangnam Style)", "country": "South Korea"},
    {"name": "MrBeast", "follower_count": 110, "description": "Famous YouTuber", "country": "USA"},
    {"name": "PewDiePie", "follower_count": 110, "description": "Swedish YouTuber", "country": "Sweden"},
    {"name": "Markiplier", "follower_count": 35, "description": "YouTuber and gamer", "country": "USA"},
    {"name": "Ninja", "follower_count": 20, "description": "Game streamer", "country": "USA"},
    {"name": "Shroud", "follower_count": 12, "description": "Professional gamer and streamer", "country": "Canada"},
    {"name": "Pokimane", "follower_count": 10, "description": "Female streamer", "country": "Morocco/Canada"},
    {"name": "Dream", "follower_count": 30, "description": "Minecraft YouTuber", "country": "USA"},
    {"name": "GeorgeNotFound", "follower_count": 15, "description": "Minecraft YouTuber", "country": "UK"},
    {"name": "TommyInnit", "follower_count": 12, "description": "Minecraft YouTuber", "country": "UK"},
    {"name": "Albert Einstein", "follower_count": 18, "description": "Theoretical physicist", "country": "Germany/USA"},
    {"name": "Stephen Hawking", "follower_count": 8, "description": "Physicist and cosmologist", "country": "UK"},
    {"name": "Nikola Tesla", "follower_count": 12, "description": "Inventor and engineer", "country": "Serbia/USA"},
    {"name": "Thomas Edison", "follower_count": 10, "description": "Inventor and entrepreneur", "country": "USA"},
    {"name": "Marie Curie", "follower_count": 8, "description": "Scientist and Nobel laureate", "country": "Poland/France"},
    {"name": "Charles Darwin", "follower_count": 7, "description": "Biologist and naturalist", "country": "UK"},
    {"name": "Isaac Newton", "follower_count": 9, "description": "Physicist and mathematician", "country": "UK"},
    {"name": "Galileo Galilei", "follower_count": 6, "description": "Astronomer and physicist", "country": "Italy"},
    {"name": "Leonardo da Vinci", "follower_count": 15, "description": "Renaissance artist and inventor", "country": "Italy"},
    {"name": "Vincent van Gogh", "follower_count": 12, "description": "Famous Dutch painter", "country": "Netherlands"},
    {"name": "Pablo Picasso", "follower_count": 10, "description": "Painter and sculptor", "country": "Spain"},
    {"name": "Frida Kahlo", "follower_count": 8, "description": "Mexican painter", "country": "Mexico"},
    {"name": "Andy Warhol", "follower_count": 6, "description": "Pop art artist", "country": "USA"},
    {"name": "Zac Efron", "follower_count": 60, "description": "Actor", "country": "USA"},
    {"name": "Miley Cyrus", "follower_count": 50, "description": "Singer and actress", "country": "USA"},
    {"name": "Demi Lovato", "follower_count": 50, "description": "Singer and actress", "country": "USA"},
    {"name": "Adele", "follower_count": 55, "description": "English singer", "country": "UK"},
    {"name": "Ed Sheeran", "follower_count": 45, "description": "Singer and songwriter", "country": "UK"},
    {"name": "Sam Smith", "follower_count": 30, "description": "Singer and songwriter", "country": "UK"},
    {"name": "Bruno Mars", "follower_count": 35, "description": "Singer and producer", "country": "USA"},
    {"name": "Kanye West", "follower_count": 30, "description": "Rapper and fashion designer", "country": "USA"},
    {"name": "Jay-Z", "follower_count": 25, "description": "Rapper and entrepreneur", "country": "USA"},
    {"name": "Snoop Dogg", "follower_count": 85, "description": "Rapper and artist", "country": "USA"},
    {"name": "Ice Cube", "follower_count": 25, "description": "Rapper and actor", "country": "USA"},
    {"name": "50 Cent", "follower_count": 35, "description": "Rapper and entrepreneur", "country": "USA"},
    {"name": "Cardi B", "follower_count": 75, "description": "American rapper", "country": "USA"},
    {"name": "Nicki Minaj", "follower_count": 75, "description": "Rapper and singer", "country": "Trinidad/USA"},
    {"name": "Megan Thee Stallion", "follower_count": 30, "description": "American rapper", "country": "USA"},
    {"name": "Doja Cat", "follower_count": 25, "description": "Singer and rapper", "country": "USA"},
    {"name": "Travis Scott", "follower_count": 50, "description": "Rapper and singer", "country": "USA"},
    {"name": "Post Malone", "follower_count": 40, "description": "Singer and rapper", "country": "USA"},
    {"name": "The Weeknd", "follower_count": 50, "description": "Canadian singer", "country": "Canada"},
    {"name": "Dua Lipa", "follower_count": 90, "description": "English singer", "country": "UK/Albania"},
    {"name": "Olivia Rodrigo", "follower_count": 35, "description": "Singer and actress", "country": "USA"},
    {"name": "Harry Styles", "follower_count": 45, "description": "Singer and actor", "country": "UK"},
    {"name": "Niall Horan", "follower_count": 20, "description": "Irish singer", "country": "Ireland"},
    {"name": "Liam Payne", "follower_count": 15, "description": "English singer", "country": "UK"},
    {"name": "Louis Tomlinson", "follower_count": 15, "description": "English singer", "country": "UK"},
    {"name": "Zayn Malik", "follower_count": 30, "description": "English singer", "country": "UK"},
    {"name": "Coldplay", "follower_count": 20, "description": "Rock band", "country": "UK"},
    {"name": "Imagine Dragons", "follower_count": 18, "description": "Rock band", "country": "USA"},
    {"name": "Maroon 5", "follower_count": 25, "description": "Pop band", "country": "USA"},
    {"name": "Linkin Park", "follower_count": 15, "description": "Rock band", "country": "USA"},
    {"name": "Metallica", "follower_count": 12, "description": "Metal band", "country": "USA"},
    {"name": "Iron Maiden", "follower_count": 10, "description": "Heavy metal band", "country": "UK"},
    {"name": "AC/DC", "follower_count": 12, "description": "Rock band", "country": "Australia"},
    {"name": "Guns N' Roses", "follower_count": 10, "description": "Rock band", "country": "USA"},
    {"name": "Nirvana", "follower_count": 15, "description": "Grunge band", "country": "USA"},
    {"name": "Pearl Jam", "follower_count": 8, "description": "Rock band", "country": "USA"},
    {"name": "Foo Fighters", "follower_count": 10, "description": "Rock band", "country": "USA"},
    {"name": "U2", "follower_count": 8, "description": "Irish rock band", "country": "Ireland"},
    {"name": "One Direction", "follower_count": 25, "description": "Pop band", "country": "UK"},
    {"name": "Westlife", "follower_count": 8, "description": "Irish pop band", "country": "Ireland"},
    {"name": "Backstreet Boys", "follower_count": 10, "description": "Pop band", "country": "USA"},
    {"name": "Spice Girls", "follower_count": 7, "description": "Pop band", "country": "UK"},
    {"name": "NSYNC", "follower_count": 6, "description": "Pop band", "country": "USA"},
    {"name": "Britney Spears", "follower_count": 45, "description": "Singer and artist", "country": "USA"},
    {"name": "Christina Aguilera", "follower_count": 25, "description": "Singer", "country": "USA"},
    {"name": "P!nk", "follower_count": 30, "description": "Singer", "country": "USA"},
    {"name": "Katy Perry", "follower_count": 45, "description": "Singer", "country": "USA"},
    {"name": "Lizzo", "follower_count": 15, "description": "Singer and rapper", "country": "USA"},
    {"name": "Halsey", "follower_count": 30, "description": "Singer", "country": "USA"},
    {"name": "Lana Del Rey", "follower_count": 25, "description": "Singer", "country": "USA"},
    {"name": "Lorde", "follower_count": 12, "description": "New Zealand singer", "country": "New Zealand"},
    {"name": "Sia", "follower_count": 20, "description": "Singer and songwriter", "country": "Australia"},
    {"name": "Ellie Goulding", "follower_count": 15, "description": "English singer", "country": "UK"},
    {"name": "Dolly Parton", "follower_count": 8, "description": "American singer and actress", "country": "USA"},
    {"name": "Oprah Winfrey", "follower_count": 25, "description": "TV host and philanthropist", "country": "USA"},
    {"name": "Ellen DeGeneres", "follower_count": 35, "description": "Comedian and TV host", "country": "USA"},
    {"name": "Jimmy Fallon", "follower_count": 15, "description": "TV host and comedian", "country": "USA"},
    {"name": "Conan O'Brien", "follower_count": 8, "description": "Comedian and TV host", "country": "USA"},
    {"name": "Stephen Colbert", "follower_count": 12, "description": "TV host and comedian", "country": "USA"},
    {"name": "Trevor Noah", "follower_count": 10, "description": "Comedian and TV host", "country": "South Africa"},
    {"name": "Hasan Minhaj", "follower_count": 5, "description": "Comedian and actor", "country": "USA"},
    {"name": "Ali Wong", "follower_count": 4, "description": "Comedian and actress", "country": "USA"},
    {"name": "Dave Chappelle", "follower_count": 7, "description": "Comedian and actor", "country": "USA"},
    {"name": "Kevin Hart", "follower_count": 175, "description": "Comedian and actor", "country": "USA"},
    {"name": "John Cena", "follower_count": 22, "description": "Wrestler and actor", "country": "USA"},
    {"name": "Dave Bautista", "follower_count": 8, "description": "Wrestler and actor", "country": "USA"},
    {"name": "Hulk Hogan", "follower_count": 9, "description": "Former wrestler", "country": "USA"},
    {"name": "Randy Orton", "follower_count": 6, "description": "Professional wrestler", "country": "USA"},
    {"name": "Roman Reigns", "follower_count": 10, "description": "Professional wrestler", "country": "USA"},
    {"name": "Rey Mysterio", "follower_count": 7, "description": "Professional wrestler", "country": "USA"},
    {"name": "John Cena", "follower_count": 22, "description": "Wrestler and actor", "country": "USA"},
    {"name": "Jason Statham", "follower_count": 12, "description": "Actor", "country": "UK"},
    {"name": "Ryan Reynolds", "follower_count": 55, "description": "Actor", "country": "Canada"},
    {"name": "Hugh Jackman", "follower_count": 30, "description": "Actor", "country": "Australia"},
    {"name": "Keanu Reeves", "follower_count": 18, "description": "Actor", "country": "Canada"},
    {"name": "Johnny Depp", "follower_count": 25, "description": "Actor", "country": "USA"},
    {"name": "Brad Pitt", "follower_count": 15, "description": "Actor and producer", "country": "USA"},
    {"name": "Leonardo DiCaprio", "follower_count": 20, "description": "Actor", "country": "USA"},
    {"name": "Tom Cruise", "follower_count": 12, "description": "Actor", "country": "USA"},
    {"name": "Angelina Jolie", "follower_count": 15, "description": "Actress", "country": "USA"},
    {"name": "Jennifer Lawrence", "follower_count": 30, "description": "Actress", "country": "USA"},
    {"name": "Emma Watson", "follower_count": 45, "description": "Actress", "country": "UK"},
    {"name": "Daniel Radcliffe", "follower_count": 15, "description": "Actor", "country": "UK"},
    {"name": "Emma Stone", "follower_count": 35, "description": "Actress", "country": "USA"},
    {"name": "Anne Hathaway", "follower_count": 25, "description": "Actress", "country": "USA"},
    {"name": "Cate Blanchett", "follower_count": 8, "description": "Actress", "country": "Australia"},
    {"name": "Lupita Nyong'o", "follower_count": 5, "description": "Actress", "country": "Kenya/Mexico"},
    {"name": "Charlize Theron", "follower_count": 10, "description": "Actress", "country": "South Africa"},
    {"name": "Natalie Portman", "follower_count": 8, "description": "Actress", "country": "Israel/USA"},
    {"name": "Scarlett Johansson", "follower_count": 70, "description": "Actress", "country": "USA"},
    {"name": "Chris Evans", "follower_count": 25, "description": "Actor", "country": "USA"},
    {"name": "Chris Pratt", "follower_count": 35, "description": "Actor", "country": "USA"},
    {"name": "Henry Cavill", "follower_count": 18, "description": "Actor", "country": "UK"},
    {"name": "Gal Gadot", "follower_count": 35, "description": "Actress", "country": "Israel"},
    {"name": "Margot Robbie", "follower_count": 28, "description": "Actress", "country": "Australia"},
    {"name": "Timothée Chalamet", "follower_count": 18, "description": "Actor", "country": "USA"},
    {"name": "Florence Pugh", "follower_count": 8, "description": "Actress", "country": "UK"},
    {"name": "Anya Taylor-Joy", "follower_count": 12, "description": "Actress", "country": "USA/UK"},
    {"name": "Tom Hardy", "follower_count": 12, "description": "Actor", "country": "UK"},
    {"name": "Benedict Cumberbatch", "follower_count": 10, "description": "Actor", "country": "UK"},
    {"name": "Tom Hiddleston", "follower_count": 8, "description": "Actor", "country": "UK"},
    {"name": "Elizabeth Olsen", "follower_count": 14, "description": "Actress", "country": "USA"},
    {"name": "Hailee Steinfeld", "follower_count": 12, "description": "Actress and singer", "country": "USA"},
    {"name": "Millie Bobby Brown", "follower_count": 22, "description": "Actress", "country": "UK"},
    {"name": "Saoirse Ronan", "follower_count": 5, "description": "Actress", "country": "Ireland"},
    {"name": "Michael B. Jordan", "follower_count": 20, "description": "Actor", "country": "USA"},
    {"name": "Chadwick Boseman", "follower_count": 10, "description": "Actor", "country": "USA"},
    {"name": "Idris Elba", "follower_count": 10, "description": "Actor", "country": "UK"},
    {"name": "Anthony Mackie", "follower_count": 8, "description": "Actor", "country": "USA"},
    {"name": "Sebastian Stan", "follower_count": 7, "description": "Actor", "country": "Romania/USA"},
    {"name": "Jake Gyllenhaal", "follower_count": 12, "description": "Actor", "country": "USA"},
    {"name": "Ryan Gosling", "follower_count": 10, "description": "Actor", "country": "Canada"},
    {"name": "Bradley Cooper", "follower_count": 15, "description": "Actor", "country": "USA"},
    {"name": "Matt Damon", "follower_count": 12, "description": "Actor", "country": "USA"},
    {"name": "Ben Affleck", "follower_count": 8, "description": "Actor", "country": "USA"},
    {"name": "Christian Bale", "follower_count": 6, "description": "Actor", "country": "UK"},
    {"name": "Robert Pattinson", "follower_count": 20, "description": "Actor", "country": "UK"},
    {"name": "Andrew Garfield", "follower_count": 10, "description": "Actor", "country": "USA/UK"},
    {"name": "Tobey Maguire", "follower_count": 6, "description": "Actor", "country": "USA"},
    {"name": "Spider-Man", "follower_count": 18, "description": "Marvel superhero", "country": "USA"},
    {"name": "Batman", "follower_count": 15, "description": "DC superhero", "country": "USA"},
    {"name": "Superman", "follower_count": 12, "description": "DC superhero", "country": "USA"},
    {"name": "Wonder Woman", "follower_count": 14, "description": "DC superhero", "country": "USA"},
    {"name": "Iron Man", "follower_count": 20, "description": "Marvel superhero", "country": "USA"},
    {"name": "Captain America", "follower_count": 16, "description": "Marvel superhero", "country": "USA"},
    {"name": "Thor", "follower_count": 14, "description": "Marvel superhero", "country": "USA"},
    {"name": "Black Panther", "follower_count": 12, "description": "Marvel superhero", "country": "USA"},
    {"name": "Deadpool", "follower_count": 10, "description": "Marvel character", "country": "USA"},
    {"name": "Venom", "follower_count": 8, "description": "Marvel character", "country": "USA"},
    {"name": "Joker", "follower_count": 12, "description": "DC villain", "country": "USA"},
    {"name": "Harley Quinn", "follower_count": 10, "description": "DC character", "country": "USA"},
    {"name": "The Dark Knight", "follower_count": 9, "description": "Batman film", "country": "USA"},
    {"name": "Inception", "follower_count": 7, "description": "Christopher Nolan film", "country": "USA/UK"},
    {"name": "Interstellar", "follower_count": 8, "description": "Sci-fi film", "country": "USA/UK"},
    {"name": "The Matrix", "follower_count": 8, "description": "Sci-fi film franchise", "country": "USA"},
    {"name": "Avatar", "follower_count": 10, "description": "Sci-fi film", "country": "USA"},
    {"name": "Titanic", "follower_count": 12, "description": "Historical romance film", "country": "USA"},
    {"name": "Jurassic Park", "follower_count": 9, "description": "Sci-fi adventure film", "country": "USA"},
    {"name": "Star Trek", "follower_count": 8, "description": "Sci-fi franchise", "country": "USA"},
    {"name": "Doctor Who", "follower_count": 6, "description": "British TV series", "country": "UK"},
    {"name": "Sherlock", "follower_count": 7, "description": "British TV series", "country": "UK"},
    {"name": "Downton Abbey", "follower_count": 4, "description": "British TV series", "country": "UK"},
    {"name": "The Crown", "follower_count": 8, "description": "British TV series", "country": "UK"},
    {"name": "House of the Dragon", "follower_count": 10, "description": "HBO series", "country": "USA"},
    {"name": "Game of Thrones", "follower_count": 25, "description": "HBO series", "country": "USA"},
    {"name": "The Walking Dead", "follower_count": 15, "description": "TV series", "country": "USA"},
    {"name": "Breaking Bad", "follower_count": 18, "description": "TV series", "country": "USA"},
    {"name": "Better Call Saul", "follower_count": 7, "description": "TV series", "country": "USA"},
    {"name": "Mad Men", "follower_count": 4, "description": "TV series", "country": "USA"},
    {"name": "The Office", "follower_count": 12, "description": "US TV series", "country": "USA"},
    {"name": "Friends", "follower_count": 20, "description": "TV series", "country": "USA"},
    {"name": "Seinfeld", "follower_count": 6, "description": "TV series", "country": "USA"},
    {"name": "The Big Bang Theory", "follower_count": 10, "description": "TV series", "country": "USA"},
    {"name": "How I Met Your Mother", "follower_count": 8, "description": "TV series", "country": "USA"},
    {"name": "Modern Family", "follower_count": 6, "description": "TV series", "country": "USA"},
    {"name": "Brooklyn Nine-Nine", "follower_count": 7, "description": "TV series", "country": "USA"},
    {"name": "Parks and Recreation", "follower_count": 5, "description": "TV series", "country": "USA"},
    {"name": "South Park", "follower_count": 8, "description": "Animated TV series", "country": "USA"},
    {"name": "Family Guy", "follower_count": 10, "description": "Animated TV series", "country": "USA"},
    {"name": "The Simpsons", "follower_count": 15, "description": "Animated TV series", "country": "USA"},
    {"name": "SpongeBob SquarePants", "follower_count": 12, "description": "Animated TV series", "country": "USA"},
    {"name": "Adventure Time", "follower_count": 6, "description": "Animated TV series", "country": "USA"},
    {"name": "Rick and Morty", "follower_count": 8, "description": "Animated TV series", "country": "USA"},
    {"name": "Demon Slayer", "follower_count": 12, "description": "Japanese anime", "country": "Japan"},
    {"name": "Jujutsu Kaisen", "follower_count": 10, "description": "Japanese anime", "country": "Japan"},
    {"name": "My Hero Academia", "follower_count": 9, "description": "Japanese anime", "country": "Japan"},
    {"name": "Death Note", "follower_count": 8, "description": "Japanese anime", "country": "Japan"},
    {"name": "Fullmetal Alchemist", "follower_count": 6, "description": "Japanese anime", "country": "Japan"},
    {"name": "Steins;Gate", "follower_count": 4, "description": "Japanese anime", "country": "Japan"},
    {"name": "Goku", "follower_count": 12, "description": "Dragon Ball character", "country": "Japan"},
    {"name": "Pikachu", "follower_count": 15, "description": "Pokemon character", "country": "Japan"},
    {"name": "Mario", "follower_count": 14, "description": "Nintendo character", "country": "Japan"},
    {"name": "Link", "follower_count": 8, "description": "Zelda character", "country": "Japan"},
    {"name": "Kirby", "follower_count": 6, "description": "Nintendo character", "country": "Japan"},
    {"name": "Samus Aran", "follower_count": 4, "description": "Metroid character", "country": "Japan"},
    {"name": "Cloud Strife", "follower_count": 5, "description": "Final Fantasy character", "country": "Japan"},
    {"name": "Solid Snake", "follower_count": 4, "description": "Metal Gear character", "country": "Japan"},
    {"name": "Kratos", "follower_count": 7, "description": "God of War character", "country": "Greece/USA"},
    {"name": "Arthur Morgan", "follower_count": 6, "description": "Red Dead Redemption 2 character", "country": "USA"},
    {"name": "Nathan Drake", "follower_count": 5, "description": "Uncharted character", "country": "USA"},
    {"name": "Lara Croft", "follower_count": 6, "description": "Tomb Raider character", "country": "UK"},
    {"name": "Master Chief", "follower_count": 5, "description": "Halo character", "country": "USA"},
    {"name": "Doom Slayer", "follower_count": 4, "description": "Doom character", "country": "USA"},
    {"name": "Geralt of Rivia", "follower_count": 6, "description": "The Witcher character", "country": "Poland"},
    {"name": "Aloy", "follower_count": 5, "description": "Horizon Zero Dawn character", "country": "USA"},
    {"name": "Ellie Williams", "follower_count": 7, "description": "The Last of Us character", "country": "USA"},
    {"name": "Joel Miller", "follower_count": 6, "description": "The Last of Us character", "country": "USA"},
    {"name": "Spyro the Dragon", "follower_count": 4, "description": "Video game character", "country": "USA"},
    {"name": "Crash Bandicoot", "follower_count": 5, "description": "Video game character", "country": "USA"},
    {"name": "Rayman", "follower_count": 4, "description": "Video game character", "country": "France"},
    {"name": "The Legend of Zelda", "follower_count": 12, "description": "Video game franchise", "country": "Japan"},
    {"name": "Metroid", "follower_count": 5, "description": "Video game franchise", "country": "Japan"},
    {"name": "Final Fantasy", "follower_count": 10, "description": "Video game franchise", "country": "Japan"},
    {"name": "Kingdom Hearts", "follower_count": 6, "description": "Video game franchise", "country": "Japan"},
    {"name": "Resident Evil", "follower_count": 8, "description": "Video game franchise", "country": "Japan"},
    {"name": "Silent Hill", "follower_count": 5, "description": "Video game franchise", "country": "Japan"},
    {"name": "Street Fighter", "follower_count": 6, "description": "Video game franchise", "country": "Japan"},
    {"name": "Mortal Kombat", "follower_count": 8, "description": "Video game franchise", "country": "USA"},
    {"name": "Tekken", "follower_count": 5, "description": "Video game franchise", "country": "Japan"},
    {"name": "Soulcalibur", "follower_count": 3, "description": "Video game franchise", "country": "Japan"},
    {"name": "Overwatch", "follower_count": 10, "description": "Video game", "country": "USA"},
    {"name": "Apex Legends", "follower_count": 8, "description": "Video game", "country": "USA"},
    {"name": "Counter-Strike", "follower_count": 9, "description": "Video game", "country": "USA"},
    {"name": "Dota 2", "follower_count": 7, "description": "Video game", "country": "USA"},
    {"name": "League of Legends", "follower_count": 15, "description": "Video game", "country": "USA"},
    {"name": "World of Warcraft", "follower_count": 8, "description": "Video game", "country": "USA"},
    {"name": "StarCraft", "follower_count": 5, "description": "Video game", "country": "USA"},
    {"name": "Diablo", "follower_count": 6, "description": "Video game franchise", "country": "USA"},
    {"name": "Fallout", "follower_count": 8, "description": "Video game franchise", "country": "USA"},
    {"name": "Elder Scrolls", "follower_count": 9, "description": "Video game franchise", "country": "USA"},
    {"name": "Mass Effect", "follower_count": 6, "description": "Video game franchise", "country": "Canada/USA"},
    {"name": "Dragon Age", "follower_count": 5, "description": "Video game franchise", "country": "Canada/USA"},
    {"name": "Bioshock", "follower_count": 5, "description": "Video game franchise", "country": "USA"},
    {"name": "Assassin's Creed", "follower_count": 12, "description": "Video game franchise", "country": "France"},
    {"name": "Far Cry", "follower_count": 7, "description": "Video game franchise", "country": "France"},
    {"name": "Watch Dogs", "follower_count": 5, "description": "Video game franchise", "country": "France"},
    {"name": "The Division", "follower_count": 4, "description": "Video game franchise", "country": "France"},
    {"name": "Tom Clancy's Rainbow Six", "follower_count": 6, "description": "Video game franchise", "country": "France"},
    {"name": "Splinter Cell", "follower_count": 4, "description": "Video game franchise", "country": "France"},
    {"name": "Prince of Persia", "follower_count": 5, "description": "Video game franchise", "country": "France"},
    {"name": "Beyond Good & Evil", "follower_count": 3, "description": "Video game franchise", "country": "France"},
    {"name": "Alan Wake", "follower_count": 4, "description": "Video game", "country": "Finland"},
    {"name": "Control", "follower_count": 4, "description": "Video game", "country": "Finland"},
    {"name": "Max Payne", "follower_count": 4, "description": "Video game franchise", "country": "Finland/USA"},
    {"name": "Angry Birds", "follower_count": 8, "description": "Mobile game", "country": "Finland"},
    {"name": "Clash of Clans", "follower_count": 10, "description": "Mobile game", "country": "Finland"},
    {"name": "Clash Royale", "follower_count": 8, "description": "Mobile game", "country": "Finland"},
    {"name": "Brawl Stars", "follower_count": 7, "description": "Mobile game", "country": "Finland"},
    {"name": "Candy Crush", "follower_count": 6, "description": "Mobile game", "country": "Sweden"},
    {"name": "Subway Surfers", "follower_count": 5, "description": "Mobile game", "country": "Denmark"},
    {"name": "Pokémon GO", "follower_count": 10, "description": "Mobile game", "country": "USA/Japan"},
    {"name": "Mario Kart", "follower_count": 8, "description": "Racing game", "country": "Japan"},
    {"name": "Gran Turismo", "follower_count": 5, "description": "Racing game", "country": "Japan"},
    {"name": "Forza Horizon", "follower_count": 6, "description": "Racing game", "country": "UK/USA"},
    {"name": "Need for Speed", "follower_count": 7, "description": "Racing game", "country": "USA"},
    {"name": "F1", "follower_count": 6, "description": "Racing game", "country": "UK"},
    {"name": "FIFA", "follower_count": 15, "description": "Football video game", "country": "Canada"},
    {"name": "PES/eFootball", "follower_count": 8, "description": "Football video game", "country": "Japan"},
    {"name": "NBA 2K", "follower_count": 10, "description": "Basketball video game", "country": "USA"},
    {"name": "Madden NFL", "follower_count": 6, "description": "American football game", "country": "USA"},
    {"name": "MLB The Show", "follower_count": 4, "description": "Baseball game", "country": "USA"},
    {"name": "Tiger Woods", "follower_count": 8, "description": "Golfer", "country": "USA"},
    {"name": "Rory McIlroy", "follower_count": 5, "description": "Golfer", "country": "UK"},
    {"name": "Serena Williams", "follower_count": 15, "description": "Tennis player", "country": "USA"},
    {"name": "Venus Williams", "follower_count": 8, "description": "Tennis player", "country": "USA"},
    {"name": "Naomi Osaka", "follower_count": 6, "description": "Tennis player", "country": "Japan"},
    {"name": "Coco Gauff", "follower_count": 5, "description": "Tennis player", "country": "USA"},
    {"name": "Roger Federer", "follower_count": 12, "description": "Tennis player", "country": "Switzerland"},
    {"name": "Rafael Nadal", "follower_count": 15, "description": "Tennis player", "country": "Spain"},
    {"name": "Novak Djokovic", "follower_count": 12, "description": "Tennis player", "country": "Serbia"},
    {"name": "Andy Murray", "follower_count": 6, "description": "Tennis player", "country": "UK"},
    {"name": "Lewis Hamilton", "follower_count": 12, "description": "Formula 1 driver", "country": "UK"},
    {"name": "Max Verstappen", "follower_count": 10, "description": "Formula 1 driver", "country": "Netherlands"},
    {"name": "Charles Leclerc", "follower_count": 8, "description": "Formula 1 driver", "country": "Monaco"},
    {"name": "Lando Norris", "follower_count": 7, "description": "Formula 1 driver", "country": "UK"},
    {"name": "Daniel Ricciardo", "follower_count": 6, "description": "Formula 1 driver", "country": "Australia"},
    {"name": "Sebastian Vettel", "follower_count": 6, "description": "Formula 1 driver", "country": "Germany"},
    {"name": "Kimi Räikkönen", "follower_count": 5, "description": "Former Formula 1 driver", "country": "Finland"},
    {"name": "Fernando Alonso", "follower_count": 6, "description": "Formula 1 driver", "country": "Spain"},
    {"name": "Michael Schumacher", "follower_count": 7, "description": "Former F1 driver", "country": "Germany"},
    {"name": "Ayrton Senna", "follower_count": 6, "description": "Former F1 driver", "country": "Brazil"},
    {"name": "Niki Lauda", "follower_count": 4, "description": "Former F1 driver", "country": "Austria"},
    {"name": "James Hunt", "follower_count": 4, "description": "Former F1 driver", "country": "UK"},
    {"name": "Eliud Kipchoge", "follower_count": 5, "description": "Marathon runner", "country": "Kenya"},
    {"name": "Usain Bolt", "follower_count": 10, "description": "Sprinter", "country": "Jamaica"},
    {"name": "Michael Phelps", "follower_count": 6, "description": "Swimmer", "country": "USA"},
    {"name": "Simone Biles", "follower_count": 8, "description": "Gymnast", "country": "USA"},
    {"name": "Katie Ledecky", "follower_count": 4, "description": "Swimmer", "country": "USA"},
    {"name": "Allyson Felix", "follower_count": 4, "description": "Sprinter", "country": "USA"},
    {"name": "Carl Lewis", "follower_count": 4, "description": "Former sprinter", "country": "USA"},
    {"name": "Mohammed Ali", "follower_count": 8, "description": "Former boxer", "country": "USA"},
    {"name": "Manny Pacquiao", "follower_count": 6, "description": "Boxer and politician", "country": "Philippines"},
    {"name": "Floyd Mayweather", "follower_count": 8, "description": "Boxer", "country": "USA"},
    {"name": "Canelo Alvarez", "follower_count": 6, "description": "Boxer", "country": "Mexico"},
    {"name": "Tyson Fury", "follower_count": 5, "description": "Boxer", "country": "UK"},
    {"name": "Anthony Joshua", "follower_count": 5, "description": "Boxer", "country": "UK"},
    {"name": "Babe Ruth", "follower_count": 4, "description": "Baseball player", "country": "USA"},
    {"name": "Joe Montana", "follower_count": 3, "description": "American football player", "country": "USA"},
    {"name": "Tom Brady", "follower_count": 12, "description": "American football player", "country": "USA"},
    {"name": "Patrick Mahomes", "follower_count": 8, "description": "American football player", "country": "USA"},
    {"name": "Aaron Rodgers", "follower_count": 6, "description": "American football player", "country": "USA"},
    {"name": "Lamar Jackson", "follower_count": 5, "description": "American football player", "country": "USA"},
    {"name": "Josh Allen", "follower_count": 4, "description": "American football player", "country": "USA"},
    {"name": "John Elway", "follower_count": 3, "description": "Former NFL player", "country": "USA"},
    {"name": "Pele", "follower_count": 12, "description": "Brazilian footballer legend", "country": "Brazil"},
    {"name": "Diego Maradona", "follower_count": 10, "description": "Argentine footballer legend", "country": "Argentina"},
    {"name": "Zinedine Zidane", "follower_count": 8, "description": "Former footballer", "country": "France"},
    {"name": "Ronaldinho", "follower_count": 10, "description": "Brazilian footballer", "country": "Brazil"},
    {"name": "Kaká", "follower_count": 8, "description": "Brazilian footballer", "country": "Brazil"},
    {"name": "David Beckham", "follower_count": 15, "description": "Former footballer", "country": "UK"},
    {"name": "Wayne Rooney", "follower_count": 6, "description": "Former footballer", "country": "UK"},
    {"name": "Steven Gerrard", "follower_count": 5, "description": "Former footballer", "country": "UK"},
    {"name": "Frank Lampard", "follower_count": 5, "description": "Former footballer", "country": "UK"},
    {"name": "Thierry Henry", "follower_count": 6, "description": "Former footballer", "country": "France"},
    {"name": "Robert Lewandowski", "follower_count": 8, "description": "Polish footballer", "country": "Poland"},
    {"name": "Mohamed Salah", "follower_count": 18, "description": "Egyptian footballer", "country": "Egypt"},
    {"name": "Sadio Mané", "follower_count": 10, "description": "Senegalese footballer", "country": "Senegal"},
    {"name": "Kylian Mbappé", "follower_count": 45, "description": "French footballer", "country": "France"},
    {"name": "Erling Haaland", "follower_count": 25, "description": "Norwegian footballer", "country": "Norway"},
    {"name": "Vinicius Jr", "follower_count": 15, "description": "Brazilian footballer", "country": "Brazil"},
    {"name": "Jude Bellingham", "follower_count": 10, "description": "English footballer", "country": "UK"},
    {"name": "Bukayo Saka", "follower_count": 8, "description": "English footballer", "country": "UK"},
    {"name": "Phil Foden", "follower_count": 7, "description": "English footballer", "country": "UK"},
    {"name": "Declan Rice", "follower_count": 5, "description": "English footballer", "country": "UK"},
    {"name": "Harry Kane", "follower_count": 12, "description": "English footballer", "country": "UK"},
    {"name": "Joshua Kimmich", "follower_count": 5, "description": "German footballer", "country": "Germany"},
    {"name": "Toni Kroos", "follower_count": 6, "description": "German footballer", "country": "Germany"},
    {"name": "Manuel Neuer", "follower_count": 7, "description": "German footballer", "country": "Germany"},
    {"name": "Thomas Müller", "follower_count": 6, "description": "German footballer", "country": "Germany"},
    {"name": "Gianluigi Donnarumma", "follower_count": 5, "description": "Italian footballer", "country": "Italy"},
    {"name": "Giorgio Chiellini", "follower_count": 4, "description": "Italian footballer", "country": "Italy"},
    {"name": "Lorenzo Insigne", "follower_count": 4, "description": "Italian footballer", "country": "Italy"},
    {"name": "Marco Verratti", "follower_count": 4, "description": "Italian footballer", "country": "Italy"},
]
